name: Setup Ansible
description: Install Ansible in an isolated virtualenv
inputs:
  version:
    required: true
    description: Ansible version to install (e.g. "2.20.1")

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Restore venv cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: ansible-${{ runner.os }}-${{ inputs.version }}

    - name: Create virtualenv
      shell: bash
      run: |
        if [ ! -d ".venv" ]; then
          python -m venv .venv
        fi

    - name: Install Ansible
      shell: bash
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install ansible==${{ inputs.version }}

    - name: Verify Ansible
      shell: bash
      run: |
        source .venv/bin/activate
        ansible --version