name: Setup Ansible
description: Install Ansible in an isolated virtualenv
inputs:
  version:
    required: true
    description: Ansible Core version to install (e.g. "2.20.2")

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Restore venv cache
      uses: actions/cache@v6
      with:
        path: .venv
        key: ansible-${{ runner.os }}-${{ inputs.version }}

    - name: Create virtualenv
      shell: bash
      run: |
        if [ ! -d ".venv" ]; then
          python -m venv .venv
        fi

    - name: Install ansible-core if needed
      shell: bash
      run: |
        source .venv/bin/activate

        if ansible-playbook --version 2>/dev/null | grep -q "core ${{ inputs.version }}"; then
          echo "Ansible Core ${{ inputs.version }} already installed, skipping."
        else
          echo "Installing Ansible Core ${{ inputs.version }}"
          python -m pip install --upgrade pip
          python -m pip install ansible-core==${{ inputs.version }}
        fi

    - name: Verify Ansible
      shell: bash
      run: |
        source .venv/bin/activate
        ansible-playbook --version

    - name: Add venv to PATH
      shell: bash
      run: |
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
