name: Setup Ansible
description: Installs Ansible and its dependencies
inputs:
  version:
    required: true
    description: Ansible version to install (e.g., "2.10.7")
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-${{ inputs.version }}-${{ hashFiles('**/requirements.txt') }}
    
    - name: Install packages
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install -r requirements.txt
        else
          python -m pip install ansible==${{ inputs.version }}
        fi
    
branding:
    icon: 'terminal'
    color: 'blue'